// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/trading.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandleRequest) Reset() {
	*x = CandleRequest{}
	mi := &file_proto_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandleRequest) ProtoMessage() {}

func (x *CandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandleRequest.ProtoReflect.Descriptor instead.
func (*CandleRequest) Descriptor() ([]byte, []int) {
	return file_proto_trading_proto_rawDescGZIP(), []int{0}
}

func (x *CandleRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CandleRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *CandleRequest) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CandleRequest) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CandleRequest) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CandleRequest) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *CandleRequest) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CandleRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"` // "BUY", "SELL", "NONE"
	Size          float64                `protobuf:"fixed64,3,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_proto_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_trading_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SignalResponse) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *SignalResponse) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SignalResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_trading_proto protoreflect.FileDescriptor

const file_proto_trading_proto_rawDesc = "" +
	"\n" +
	"\x13proto/trading.proto\x12\atrading\"\xcb\x01\n" +
	"\rCandleRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\x01R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\"n\n" +
	"\x0eSignalResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x01R\x04size\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp2O\n" +
	"\x0fStrategyService\x12<\n" +
	"\tGetSignal\x12\x16.trading.CandleRequest\x1a\x17.trading.SignalResponseB/Z-github.com/supanut9/trading-bot/proto/tradingb\x06proto3"

var (
	file_proto_trading_proto_rawDescOnce sync.Once
	file_proto_trading_proto_rawDescData []byte
)

func file_proto_trading_proto_rawDescGZIP() []byte {
	file_proto_trading_proto_rawDescOnce.Do(func() {
		file_proto_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trading_proto_rawDesc), len(file_proto_trading_proto_rawDesc)))
	})
	return file_proto_trading_proto_rawDescData
}

var file_proto_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trading_proto_goTypes = []any{
	(*CandleRequest)(nil),  // 0: trading.CandleRequest
	(*SignalResponse)(nil), // 1: trading.SignalResponse
}
var file_proto_trading_proto_depIdxs = []int32{
	0, // 0: trading.StrategyService.GetSignal:input_type -> trading.CandleRequest
	1, // 1: trading.StrategyService.GetSignal:output_type -> trading.SignalResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trading_proto_init() }
func file_proto_trading_proto_init() {
	if File_proto_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trading_proto_rawDesc), len(file_proto_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trading_proto_goTypes,
		DependencyIndexes: file_proto_trading_proto_depIdxs,
		MessageInfos:      file_proto_trading_proto_msgTypes,
	}.Build()
	File_proto_trading_proto = out.File
	file_proto_trading_proto_goTypes = nil
	file_proto_trading_proto_depIdxs = nil
}
